### ISSUE TITLE
Mudar idioma default para português e colocar arquivos no system

### ISSUE THREAD

**Issue by marcelod** [marcelod/initerror#5]
https://github.com/CIBr/CodeIgniter-Portuguese-BR/tree/master/application/language/portuguese-br

**Comment by marcelod** [comment]
ok

**Comment by oficialboss1260** [comment]
Ele ta invalido

**Comment by marcelod** [comment]
> Ele ta invalido

sim, mas pode ser encontrado aqui por exemplo
https://github.com/bralpassos/CodeIgniter-Portuguese-BR/tree/master/application/language/portuguese-br

**Comment by NalaBlackTrava** [comment]
Oi, eu entrei agora no GitHub e eu entendi o que é o link e qual é a lógica, mas eu não faço ideia de como "ativar" a tradução do site, pode me ajudar?

**Comment by gladson25** [comment]
> Oi, eu entrei agora no GitHub e eu entendi o que é o link e qual é a lógica, mas eu não faço ideia de como "ativar" a tradução do site, pode me ajudar?

Tô na mesma...

**Comment by Bug404erro** [comment]
Eu também moço

**Comment by Alexfoxhound** [comment]
????????????????

**Comment by Bezalleell** [comment]
Boa noite tem como a genta alterar o idioma do github para Potuguês Br?

**Comment by gegezin** [comment]
como muda o bendito do idioma para portugues

**Comment by nicolashenr** [comment]
a mesma coisa aqui

**Comment by NatiEliz** [comment]
Acho que nao tem como pessualll..  :( bjs

**Comment by CaueMartinsFerreira** [comment]
#queroportugues

**Comment by iEvolutingx** [comment]
> como muda o bendito do idioma para portugues

adiciona extensão de tradução

**Comment by Bruskia** [comment]
.... Complicado mais é a vida. rs!

**Comment by Rianpedro15** [comment]
> [https://github.com/CIBr/CodeIgniter-Portuguese-BR/tree/master/application/idioma/portuguese-br](https://github.com/CIBr/CodeIgniter-Portuguese-BR/tree/master/application/language/portuguese-br)

Não ta funcionando

**Comment by Rianpedro15** [comment]
Não ta funcionando

**Comment by Rianpedro15** [comment]
Não ta fun - cionando

**Comment by ghost** [comment]
bem amigos, nao funciona 😔

**Comment by Fernandovisenfad** [comment]
Ta de brincs

**Comment by PerryAraujo** [comment]
nao funciona pessoal 🥺
