### ISSUE TITLE
anime

### ISSUE THREAD

**Issue by Altairessantos** [marcelod/initerror#8]
codigo-css-completo.txt
html, body, h1, h2, h3, h4, ul, li
{
    margin: 0px;
    padding: 0px;

}
h1 img
{
    display: block;
}
img
{
    border: 0px;
}
a {
    color: #fff;
    }
a:hover {
    color: #FFA405;
}
.left {
    float: left;
}
.rigth 
{
    float: right
}
.clear{
clear: both;
}
body
{
    background: rgb(80,70,52) url(images/fundo.jpg)
        no-repeat fixed center;
text-align: center;
font-family: "verdana", arial, sans-serif;
color: rgba(105, 95, 76, 0.60);
padding-bottom: 10px;
    background-size: cover;
    background-blend-mode: exclusion;
}
/**layout**/
#wrapper
{
    text-align: left;
    margin: 37px auto;
    width: 672px;
    background: #ffffff;
    position: relative;
}
#header
{
    background: #D9D1BC;
    height: 266px;
    background-size: contain;
    padding-left: 10px;
    padding-top: 10px;    
}
#header .dark
{
    width: 150px;
height: 250px;
}
#logo
{
    position: absolute;
top: 30px;
left: 200px;
width: 170px;
color: #52616E;
}
#logo h1
{
    font: bold 24px "arial narrow", arial, sans-serif;
}
logo p
{
    margin: 0;
font-weight: bold
}
#cart
{
    position: absolute;
top: 20px;
left: 454px;
    width: 208px;
background: rgba(16, 65, 145, 0.7);
width: 209px;
border-radius: 15px;
}
#cart-cart
{
    background: 9px 11px url(images/cart.gif)
no-repeat; 
}
#cart-cart
{
    padding: 8px 8px 8px 60px;
color: #fff;
}
#cart p
{
    margin: 0;
}
#cart .orange
{
    color: #FFB400;
font-size: 0.5rem;
}
#cart a 
{
    color: #fff;
font-size: 0.6rem
}
cart a:hover
{
    color:#FFB400;
    font-size: 0.8rem;;
}
#nav
{
    background: rgba(16, 65, 145, 0.7);
    position: absolute;
        top: 101px;
    left: 187px;
        width: 480px;
        padding: 9px 0;
        text-align: center;
        border-radius:8px;
}
#nav li
{
    list-style: none;
display: inline;
    color: #fff;
}
nav a 
{
    text-decoration: none;
    color: #fff;
        font-weight: bold;
    font-size: 0.8rem;
 }
#nav a :hover
{
    text-decoration: underline;
    color: #000;
    font-style: italic;
}
#gallery
{
    position: absolute;
top: 155px;
left: 187px;
width: 480px;
}
#gallery li
{
    list-style: none;
text-indent: 16px;
float:left;
overflow: hidden;
height: 111px
}
#gallery .pic1
{
    width: 120px;
}
#gallery .pic2
{
    width: 120px;
}
#gallery .pic3
{
    width: 120px
}
#gallery .pic4
{
 width: 120px;  
}
#gallery img
{
    width: 80%
}
#body
{
    padding-top: 3px;
    background-color:#fff;
}
#categories
{
    float: left;
width:  195px;
}
seasonal, #collection
{
    float: right;
    width: 474px;
    background: #D4CAB6;
    margin-bottom: 2px;
}
#seasonal .inner
{
    padding: 0.1px 0.3px;
height: 240px;
}
#seasonal .inner iframe
{
    height: 100%;
width:71%;
border: 180px ;
}
#collection .inner
{
    padding: 10px 12px;
height: 150px
}
#seasonal p, #collection p
{
    margin: 0.9rem 0;
}

**Comment by marcelod** [comment]
> codigo-css-completo.txt
> html, body, h1, h2, h3, h4, ul, li
> {
> margin: 0px;
> padding: 0px;
> 
> }
> h1 img
> {
> display: block;
> }
> img
> {
> border: 0px;
> }
> a {
> color: #fff;
> }
> a:hover {
> color: #FFA405;
> }
> .left {
> float: left;
> }
> .rigth
> {
> float: right
> }
> .clear{
> clear: both;
> }
> body
> {
> background: rgb(80,70,52) url(images/fundo.jpg)
> no-repeat fixed center;
> text-align: center;
> font-family: "verdana", arial, sans-serif;
> color: rgba(105, 95, 76, 0.60);
> padding-bottom: 10px;
> background-size: cover;
> background-blend-mode: exclusion;
> }
> /**layout**/
> #wrapper
> {
> text-align: left;
> margin: 37px auto;
> width: 672px;
> background: #ffffff;
> position: relative;
> }
> #header
> {
> background: #D9D1BC;
> height: 266px;
> background-size: contain;
> padding-left: 10px;
> padding-top: 10px;
> }
> #header .dark
> {
> width: 150px;
> height: 250px;
> }
> #logo
> {
> position: absolute;
> top: 30px;
> left: 200px;
> width: 170px;
> color: #52616E;
> }
> #logo h1
> {
> font: bold 24px "arial narrow", arial, sans-serif;
> }
> logo p
> {
> margin: 0;
> font-weight: bold
> }
> #cart
> {
> position: absolute;
> top: 20px;
> left: 454px;
> width: 208px;
> background: rgba(16, 65, 145, 0.7);
> width: 209px;
> border-radius: 15px;
> }
> #cart-cart
> {
> background: 9px 11px url(images/cart.gif)
> no-repeat;
> }
> #cart-cart
> {
> padding: 8px 8px 8px 60px;
> color: #fff;
> }
> #cart p
> {
> margin: 0;
> }
> #cart .orange
> {
> color: #FFB400;
> font-size: 0.5rem;
> }
> #cart a
> {
> color: #fff;
> font-size: 0.6rem
> }
> cart a:hover
> {
> color:#FFB400;
> font-size: 0.8rem;;
> }
> #nav
> {
> background: rgba(16, 65, 145, 0.7);
> position: absolute;
> top: 101px;
> left: 187px;
> width: 480px;
> padding: 9px 0;
> text-align: center;
> border-radius:8px;
> }
> #nav li
> {
> list-style: none;
> display: inline;
> color: #fff;
> }
> nav a
> {
> text-decoration: none;
> color: #fff;
> font-weight: bold;
> font-size: 0.8rem;
> }
> #nav a :hover
> {
> text-decoration: underline;
> color: #000;
> font-style: italic;
> }
> #gallery
> {
> position: absolute;
> top: 155px;
> left: 187px;
> width: 480px;
> }
> #gallery li
> {
> list-style: none;
> text-indent: 16px;
> float:left;
> overflow: hidden;
> height: 111px
> }
> #gallery .pic1
> {
> width: 120px;
> }
> #gallery .pic2
> {
> width: 120px;
> }
> #gallery .pic3
> {
> width: 120px
> }
> #gallery .pic4
> {
> width: 120px;
> }
> #gallery img
> {
> width: 80%
> }
> #body
> {
> padding-top: 3px;
> background-color:#fff;
> }
> #categories
> {
> float: left;
> width: 195px;
> }
> seasonal, #collection
> {
> float: right;
> width: 474px;
> background: #D4CAB6;
> margin-bottom: 2px;
> }
> #seasonal .inner
> {
> padding: 0.1px 0.3px;
> height: 240px;
> }
> #seasonal .inner iframe
> {
> height: 100%;
> width:71%;
> border: 180px ;
> }
> #collection .inner
> {
> padding: 10px 12px;
> height: 150px
> }
> #seasonal p, #collection p
> {
> margin: 0.9rem 0;
> }

Opa blz, qual a finalidade desse css?
